const coupons = [{
    id: 1,

}]


const data = [
    {

        id: 1,
        topic: "All",
        Questions: [
            {
                que: "HTML stand for",
                op1: ["Hypermark Language",
                    "Hypermix language",
                    "Hypertext Markup Language",
                    "Hypertension Language"],
                correct: 'Hypertext Markup Language',
            },
            {
                que: "Which tag is used to create a check box ",
                op1: ["<checkbox>",
                    "<Input type=checkbox>",
                    "<type=checkbox",
                    "None of the above"],
                correct: '<Input type="checkbox">',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 2,
        topic: "Dynamic",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 3,
        topic: "Static",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 4,
        topic: "Suggested",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
]


export default data